name: rolify
description: The perfect app for your roleplay sessions! Play sounds in background simultaneously without using your internet connection.

version: 2.0.6+17

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.4
  equatable: ^2.0.3
  event_bus: ^2.0.0
  file_picker: ^4.6.1
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_neumorphic: ^3.2.0
  flutter_svg: ^1.1.0
  just_audio: ^0.9.24
  launch_review: ^3.0.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/launcher_icon/512px_512px.png'
  adaptive_icon_background: 'assets/launcher_icon/background.png'
  adaptive_icon_foreground: 'assets/launcher_icon/ic_launcher_foreground.png'

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/
    - assets/launcher_icon/
    - assets/icons/
  fonts:
    - family: AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
    - family: Inter-Regular.ttf
      fonts:
        - asset: fonts/Inter-Regular.ttf
