name: rolify
description: The perfect app for your roleplay sessions! Play sounds in background simultaneously without using your internet connection.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.6+17

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.4
  equatable: ^2.0.3
  event_bus: ^2.0.0
  file_picker: ^4.6.1
  firebase_analytics: ^9.1.10 
  firebase_remote_config: ^2.0.9
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_neumorphic: ^3.2.0
  flutter_svg: ^1.1.0
  flutter_tts: ^3.4.0
  just_audio: ^0.9.24
  launch_review: ^3.0.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.3

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/512px_512px.png"
  adaptive_icon_background: "assets/launcher_icon/background.png"
  adaptive_icon_foreground: "assets/launcher_icon/ic_launcher_foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/
    - assets/launcher_icon/
    - assets/icons/
    - assets/icons/2.0x/
    - assets/icons/3.0x/
  fonts:
    - family:  AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
    - family:  Inter-Regular.ttf
      fonts:
        - asset: fonts/Inter-Regular.ttf
